# Generated by Django 3.0.5 on 2021-02-22 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210221_1832'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-publish',)},
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='unknown', max_length=150),
            preserve_default=False,
        ),
    ]
